[build]
  publish = "."
  command = "cd netlify/functions && npm install && cd ../.. && npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200