[build]
  publish = "."
  command = "echo 'Replacing API key placeholder...' && sed -i.bak 's/ANTHROPIC_API_KEY_PLACEHOLDER/'\"$VITE_LLM_API_KEY\"'/g' index.html && echo 'Replacement complete' && npm run build"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 